### ISSUE TITLE
Fetching imposters

### ISSUE THREAD

**Issue by npetter** [mattherman/MbDotNet#61]
Hi, I was wondering if you've considered adding support for retrieving replayable imposters? E.g. GET /imposters?replayable=true. I am facing an issue where I need to be able to persist the request/responses of a mountebank instance that has been in proxy mode and later re-use that. If you have no plans for that, would you accept a PR adding support? I would rather support this project than make my own implementation.

**Comment by mattherman** [comment]
I can take a deeper look at this later today. I think it shouldn't be too difficult, but I may need to change the way imposters are retrieved today to make it a little simpler.

Can you give me a little more information on your use case though so that I'm better able to meet your needs? I'm not super familiar with the use of proxies in mountebank. 

If I'm understanding correctly, you are using a proxy imposter to capture request/responses and then need to be able to retrieve the imposters (with the `replayable` flag) so that you can persist them and later re-create them with the same stubs?

**Comment by npetter** [comment]
Hi, thank you for the prompt reply. The use case is basically to have a battery of smoke tests for my service. However, it depends on external services X and Y, but I would like to test it in isolation without those dependencies. So here's what I do:

1. Configure my service to point X and Y to the Mountebank host
2. Run my scenario tests with Mountebank in proxy mode
3. Fetch the recorded data from Mountebank and save it to a json file (today manually with "mb save --savefile impostorsPopulated.json"
4. Prepare for running the tests by giving the recordings back to Mountebank
5. Run tests (Mountebank now replies exactly what it recorded earlier for service X and Y)

The reason I need the requests/responses from Mountebank is because I will do the recordings at an earlier time, and the Mountebank instance will be recycled. I think your understanding is correct. The problem is that I am not yet very familiar with Mountebank, so I may use the wrong terms (imposter, proxy, etc). Let me know if I only confused the discussion!

**Comment by mattherman** [comment]
Thanks, that was perfect. I will hopefully get some time to start on this soon. If not today, then in the next few days. I have some ideas on how to reorganize the imposter retrieval code that will not only improve on it in general, but should also meet your needs. I will keep you updated.

**Comment by npetter** [comment]
Thanks! Please let me know if you require any more information, or coding help.

**Comment by mattherman** [comment]
Right now the methods that retrieve imposters only return types (e.g. `RetrievedHttpImposter`) with a subset of information on them, not the entire imposter. I had hoped to find a way to change imposter retrieval to include the entire imposter. My attempt at that was to have the "retrieved" imposter types extend the actual imposters, such that `RetrievedHttpImposter` -> `HttpImposter`. By doing that, you could retrieve those imposters, serialize them to json and save them, and later deserialize them and submit them.

Unfortunately, this approach immediately ran into issues since the predicates/responses on the imposters' stubs are collections of abstract base classes (`PredicateBase`/`ResponseBase`) so during deserialization there is no way for it to automatically know what derived type it should create (e.g. `ContainsPredicate`, `EqualsPredicate`, etc.). The only way I could get this to work would be to write my own custom deserialization code. I would also need to expose that code in the library so that you could use it to deserialize the imposter json in your saved file.

While not as simple as I had hoped, it would be possible to make that change. However, it got me thinking more about your use case and I'm not entirely sure it is something this library should support. The intended purpose of this project was to make it easier for people to create imposters without needing to understand the underlying json format that mountebank expects. If you plan to re-use the imposters by simply saving/loading them via json, the library is not providing you a lot of value. Since this is something that is already supported by the mountebank executable instead of being related to making requests to the mountebank service, I would lean towards utilizing that the way you have been. The one part that this library would be meant to handle is the initial creation of the proxy imposters for the purpose of capturing the requests. Unfortunately, it does not yet support that, although I plan to add it if possible.

I'm definitely open to debate on this point and I have not completely settled on this decision. It is entirely possible I have misunderstood something. Is there some reason I have not anticipated that you cannot continue using the save/reload functionality of the executable itself?
