### ISSUE TITLE
Body as String, not Json object

### ISSUE THREAD

**Issue by kirillvet** [mattherman/MbDotNet#62]
MbDotNet 4.3.0(Nuget)

**I create imposter:**
var complexPredicateFields = new HttpPredicateFields
            {
                Method = Method.Post,
                Path = "/bm-reportbcsrus/brokerReportRUS/reportData",
                Headers = new Dictionary<string, string> { { "Content-Type", "application/json" } }
            };
var complexPredicate = new EqualsPredicate<HttpPredicateFields>(complexPredicateFields);
           var bodyPredicateFields = new HttpPredicateFields()
            {
                RequestBody = "{ \"title\": \"Harry Potter\" }"
            };
            var bodyPredicate = new EqualsPredicate<HttpPredicateFields>(bodyPredicateFields, true, "$!", null);
_imposter.AddStub().On(complexPredicate).On(bodyPredicate).ReturnsJson(HttpStatusCode.OK, response);
_mountebankClient.Submit(_imposter);
            

**Then result imposter is:**
    {
  "predicates": [
    {
      "equals": {
        "path": "/bm-reportbcsrus/brokerReportRUS/reportData",
        "method": "POST",
        "headers": {
          "Content-Type": "application/json"
        }
      },
      "caseSensitive": false
    },
    {
      "equals": {
        "body": "{ title: Harry Potter }"//why it is in quotes?
      },
      "caseSensitive": true,
      "except": "$!"
    }
  ],
}

**So, i want this:**
"equals": { "body": { "title": "Harry Potter" } },
**but i got this:**
"equals": { "body": "{ title: Harry Potter }" }

I want use json object in body, not string

**Comment by kirillvet** [comment]
i think RequestBody must be a object

        /// <summary>
        /// The request body
        /// </summary>
        [JsonProperty("body", NullValueHandling = NullValueHandling.Ignore)]
        public string RequestBody { get; set; }

i decide my problem like this, but i think it is dirty
public class BodyPredicateFields : PredicateFields
    {
        [JsonProperty("body", NullValueHandling = NullValueHandling.Ignore)]
        public new object RequestBody { get; set; }
    }

**Comment by mattherman** [comment]
Hmm, I think you're right. I thought the `body` property was a string based on the [predicate contract documentation](http://localhost:2525/docs/api/contracts), but I see them setting it to objects in the examples. 

I figured it would work fine since the HTTP request body IS a string, but I think mountebank is treating it special when the content type is `application/json`.  It is treating the body as a JSON string rather than letting the string be the content, so when it compares the string (which happens to contain the json) with the actual expected JSON, it fails.

There are a couple workarounds that you could use:

1. Remove the part of the predicate that matches `Content-Type:application/json`. With this gone, the imposter worked as expected even with `string RequestBody`.
2. Do not use an `EqualsPredicate` for the `RequestBody` matching. Use something more relaxed like `ContainsPredicate` that does not require an exact match.

Either of those should get you a working imposter for now. It looks like your suggested change would work and it shouldn't be a breaking change since `string > object`. I'll work on this soon.

**Comment by mattherman** [comment]
I'm merging this change into master right now: #63 
I'll work on getting it into the v4 branch and published soon.

**Comment by mattherman** [comment]
A v4.3.1 package has been published and should be available soon.
