### ISSUE TITLE
Specify defaulResponse creation parameter

### ISSUE THREAD

**Issue by dmitriyanikin** [mattherman/MbDotNet#64]
Hi! I want to set other status code for default response to send if no predicate matches. But [Imposter](https://github.com/mattherman/MbDotNet/blob/master/MbDotNet/Models/Imposters/Imposter.cs) hasn't got `DefaultResponse` property. Seems there is no other way to do that.

**Comment by mattherman** [comment]
I can try to find time to add this property, but for now you can accomplish this by adding an additional stub on your imposters with the default.

For example:
```
imposter.AddStub()
    .OnPathAndMethodEqual("/create", Method.Post)
    .ReturnsStatus(HttpStatusCode.Created);

imposter.AddStub()
    .ReturnsStatus(HttpStatusCode.InternalServerError);
```

Since mountebank will check for matching stubs in the order they are added, any matching requests for the "create" endpoint will get the proper 201 response, but anything that does not match will get the default 500 response. As long as you add your default response as the last stub on your imposter, you should be able to configure any default you would like.

I agree that the property on the imposter itself is a lot simpler than doing it this way so I will keep this issue open to remind myself to add that at some point.

**Comment by mattherman** [comment]
Added in #87
